# -*- coding: utf-8 -*-
"""hf_ic_llm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gn8O-jNZqzHmNwvX1lsmj-OUqcbXNwyb
"""

from huggingface_hub import InferenceClient

# Get HF Key
from google.colab import userdata
hugging_face_key = userdata.get('HUGGINGFACE_KEY')

model_id = "mistralai/Mistral-7B-Instruct-v0.2"
client = InferenceClient(model=model_id, token = hugging_face_key)

response = client.text_generation(
    "Which are important cities in Australia?")
print(response)
